DDF-3915 Documentation, cofiguration, scipt, UI changes

diff --git a/distribution/ddf-common/src/main/resources/bin/ddf b/distribution/ddf-common/src/main/resources/bin/ddf
--- a/distribution/ddf-common/src/main/resources/bin/ddf
+++ b/distribution/ddf-common/src/main/resources/bin/ddf
@@ -1,23 +1,213 @@
 #!/bin/sh
 
-SCRIPTDIR=$(dirname "$0")
+# CONFIGURATION OPTIONS
+# -----------------------------------------------------------------------------
+
+# Use "true" or "false" to control these options.
+SOLR_REQUIRE_TWO_WAY_TLS=true
+
+# Set to false if Solr runs on a different host than DDF
+SOLR_DENY_REMOTE_REQUESTS=true
+
+# -----------------------------------------------------------------------------
+
+# Store arguments for use in local functions
+FIRST_ARGUMENT=$1
+ALL_ARGUMENTS=$@
+
+# Useful directories
+SCRIPTDIR=$(dirname $0)
+HOME_DIR=$(cd "${SCRIPTDIR}/.."; pwd -P)
+
+# Declare Karaf executable's return code
+KARAF_EXEC_RC=-1
+
+# Useful files
+PROPERTIES_FILE=$HOME_DIR/etc/system.properties
+RESTART_FILE="$SCRIPTDIR/restart.jvm"
+SOLR_EXEC=${HOME_DIR}/solr/bin/solr
+
+# Extract the value of a property from a Java properties file
+# This function does not handle multi-line properties
+get_property() {
+    grep ^$1= "$PROPERTIES_FILE" | cut -d '=' -f2
+}
+
+# Return 0 (success/true) if the first two parameters are the same string, ignoring case
+equalsIgnoreCase() {
+  local RC=1
+  if [ `echo $1 | tr [:upper:] [:lower:]` =  `echo $2 | tr [:upper:] [:lower:]` ]; then
+    RC=0
+  fi
+  return $RC
+}
+
+
+refresh_properties() {
+    # Extract values from Java properties file and construct Solr URL
+    MANAGE_SOLR=$(get_property solr.managed)
+    SOLR_PORT=$(get_property solr.http.port)
+    SOLR_CLIENT=$(get_property solr.client)
+    TEMPLATE=$(get_property solr.http.url)
+    PARTIAL_URL="$(echo $TEMPLATE | sed -e 's/\${solr.http.port}/PORT_PLACEHOLDER/')"
+    SOLR_URL=${PARTIAL_URL/"PORT_PLACEHOLDER"/$SOLR_PORT}
+}
+
+# Return 0 (success/true) if the Solr lifecycle should be managed by this script
+is_managing_solr() {
+  local RC=1
+  if [ $MANAGE_SOLR = true ]; then
+    RC=0
+  fi
+  return $RC
+}
+
+# Return 0 (success/true) if the input parameter is "https" (in any case)
+is_protocol_https() {
+   equalsIgnoreCase $1 https
+}
+
+# Return 0 (success/true) if ddf_on_error.sh created a restart file
+is_restarting() {
+    local RC=1
+    if [ -f $RESTART_FILE ]; then
+        RC=0
+    fi
+    return $RC
+}
+
+# Return 0 (success/true) if Solr must require client authentication for two-way TLS
+solr_client_auth_is_required() {
+    local RC=1
+    if is_managing_solr && is_protocol_https $SOLR_URL && [ $SOLR_REQUIRE_TWO_WAY_TLS = true ]; then
+        RC=0
+    fi
+    return $RC
+}
+
+# Return 0 (success/true) Solr should only accept requests from the same host
+solr_must_deny_remote_requests() {
+    local RC=1
+    if is_managing_solr && [ $SOLR_DENY_REMOTE_REQUESTS = true ]; then
+        RC=0
+    fi
+    return $RC
+}
+
+
+# Remove the restart file so we can detect later if restart was requested
+clear_restart_flag() {
+  rm -f $RESTART_FILE
+}
+
+# Set the appropriate option to prevent Solr from responding to remote requests
+deny_remote_connection_option() {
+    if solr_must_deny_remote_requests;  then
+      if is_protocol_https $SOLR_URL; then
+        echo "-Dsolr.jetty.host=127.0.0.1"
+      else
+        echo "-Djetty.host=127.0.0.1"
+      fi
+    fi
+}
+
+# Start Solr using Solr's script
+start_solr() {
+
+    # Does not check to see if Solr is running the Solr port; there is no guarantee
+    # the Solr server is for this instance of DDF. It could have been started elsewhere.
+    $SOLR_EXEC start -force -p $SOLR_PORT $(deny_remote_connection_option)
+    local SOLR_START_RC=$?
+        if [ "$SOLR_START_RC" -ne 0 ]; then
+            echo "WARNING! Solr start returned error code, please check Solr logs"
+        fi
+}
+
+# Set special environment variables used by Solr to configure TLS
+set_solr_https_properties() {
+
+      # Use the same key and trust stores as the DDF uses.
+      export SOLR_SSL_KEY_STORE=$HOME_DIR/$(get_property javax.net.ssl.keyStore)
+      export SOLR_SSL_KEY_STORE_PASSWORD=$(get_property javax.net.ssl.keyStorePassword)
+      export SOLR_SSL_KEY_STORE_TYPE=$(get_property javax.net.ssl.keyStoreType)
+      export SOLR_SSL_TRUST_STORE=$HOME_DIR/$(get_property javax.net.ssl.trustStore)
+      export SOLR_SSL_TRUST_STORE_PASSWORD=$(get_property javax.net.ssl.trustStorePassword)
+      export SOLR_SSL_TRUST_STORE_TYPE=$(get_property javax.net.ssl.trustStoreType)
+      # Require two-way TLS
+      export SOLR_SSL_NEED_CLIENT_AUTH=$SOLR_REQUIRE_TWO_WAY_TLS
+      export SOLR_SSL_WANT_CLIENT_AUTH=false
+}
+
+
+set_solr_memory() {
+    export SOLR_JAVA_MEM="-Xms512m -Xmx2g"
+}
+
+stop_solr() {
+    $SOLR_EXEC stop -p $SOLR_PORT
+}
+
+print_messages() {
+    echo "Home directory is $HOME_DIR"
+    echo "Solr URL is $SOLR_URL"
+    if is_managing_solr; then
+        echo "This scripts manages starting and stopping Solr"
+    fi
+    if solr_must_deny_remote_requests; then
+        echo "Solr will not accept remote requests"
+    fi
+    if solr_client_auth_is_required; then
+      echo "Solr will require client PKI authentication (two-way TLS)"
+    fi
+
+    # Provide a newline for good vertical space
+    echo ""
+}
+
+
+start_karaf() {
+    # Arguments to Karaf are optional
+    ${SCRIPTDIR}/karaf ${ALL_ARGUMENTS}
+}
+
+attempt_startup() {
+    if is_managing_solr; then
+        if [ "$SOLR_CLIENT" != "HttpSolrClient" ]; then
+            echo "ERROR! solr.managed is set to true but the solr.client is not HttpSolrClient"
+            echo "Please set solr.managed to false if you are not using the HttpSolrClient and"
+            echo "do not want DDF to be managing the solr instance."
+            # Exit code 83, for ascii code S, for Solr!
+            exit 83
+        fi
+        if is_protocol_https $SOLR_URL; then
+            set_solr_https_properties
+        fi
+        set_solr_memory
+        start_solr;
+    else
+        echo "Solr is not managed"
+    fi
+
+    # Process suspended while Karaf is running
+    start_karaf
+    KARAF_EXEC_RC=$?
+}
+
+attempt_shutdown() {
+    if is_restarting; then
+        echo "Restarting JVM..."
+        if is_managing_solr; then
+            stop_solr
+        fi
+    else
+        exit $KARAF_EXEC_RC
+    fi
+}
 
 while true; do
-  # Remove the restart file indicator so we can detect later if restart was requested
-  rm -f "${SCRIPTDIR}/restart.jvm"
-
-  # Argument to Karaf is optional.
-  # Provides ability to start Karaf in different modes, e.g., server, client, etc.
-  "${SCRIPTDIR}/karaf" "$@"
-  RC=$?
-  if [ "$1" = "daemon" ]; then
-    exit ${RC}
-  else
-    # Check if restart was requested by ddf_on_error.sh
-    if [ -f "${SCRIPTDIR}/restart.jvm" ]; then
-      echo "Restarting JVM..."
-    else
-      exit $RC
-    fi
-  fi
+    refresh_properties
+    clear_restart_flag
+    print_messages
+    attempt_startup
+    attempt_shutdown
 done
