DDF-2135 Renamed export script in catalog-core-commands and added additional status messages

diff --git a/catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export b/catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export
--- a/catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export
+++ b/catalog/core/catalog-core-commands/src/main/resources/bin/catalog-export
@@ -10,6 +10,8 @@
 
 usage() { echo "Usage: $0 <-d directory> <-z zipname> <-k keystore location> [-a alias]" 1>&2; exit 1; }
 
+JARSIGNER='jarsigner'
+
 while getopts ":d:z:k:a:" o; do
     case "${o}" in
         d)
@@ -39,9 +41,12 @@ if [ -z "${d}" ] || [ -z "${z}" ] || [ -z "${k}" ]; then
     usage
 fi
 
+echo "Connecting to running DDF and exporting catalog to ${z}..."
 ./client "catalog:dump --include-content=${z} ${d}"
-if which jarsigner >/dev/null; then
-        jarsigner -keystore ${k} ${d}/${z} ${a}
+if which ${JARSIGNER} >/dev/null; then
+        echo "Running  ${JARSIGNER} on ${z}, which will prompt you to enter the keystore password to sign the zip file..."
+         ${JARSIGNER} -keystore ${k} ${d}/${z} ${a}
 else
-    echo "Unable to find jarsigner, ensure that $JAVA_HOME and $JAVA_HOME/bin are set on the path."
+    echo "Unable to find ${JARSIGNER}, ensure that $JAVA_HOME and $JAVA_HOME/bin are set on the path."
+    exit 1
 fi
